'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const {EVIDENCE_TYPE_STYLES,EVIDENCE_TAXONOMY,evidenceTypeStyle,evidenceReference,nvqEvidenceCodes,mediaExportName,witnessRatingRows,collectPortfolioMedia,takePhotosGridLayout,compileUnitPack,compileFullPortfolioFromUnitPacks,buildKsbMatrixRows}=require('../pdf-generator.js');

assert.deepEqual(Object.keys(EVIDENCE_TAXONOMY),['LRP','LRS','LRV','LRA','DOC','WTS','RPL','OTJ','GLH']);
assert.deepEqual(takePhotosGridLayout(9),{cols:3,rows:3});
assert.equal(EVIDENCE_TYPE_STYLES.voice.short,'LRA');assert.equal(evidenceTypeStyle('Talk About It').short,'LRA');
assert.equal(mediaExportName('LRA',5,['K22'],'webm'),'LRA-05 - Learner Reflective Audio - K22.webm');
const ratings=witnessRatingRows({scores:{A:1,B:2,C:3},ratingLabels:{A:'Safety',B:'Quality',C:'Conduct'}});
assert.deepEqual(ratings,[{label:'Safety',rating:1},{label:'Quality',rating:2},{label:'Conduct',rating:3}]);
const app=fs.readFileSync('app.js','utf8'),pdf=fs.readFileSync('pdf-generator.js','utf8'),css=fs.readFileSync('styles.css','utf8');
const compiledFn=app.slice(app.indexOf('function compiledEvidencePackTile'),app.indexOf('async function deleteSavedEvidencePdf'));
assert.match(compiledFn,/Preview EP/);assert.match(compiledFn,/Download EP/);assert.doesNotMatch(compiledFn,/submitted-evidence-row/);
assert.doesNotMatch(app.slice(app.indexOf('function renderAssignment(){'),app.indexOf('function outcomePhotoControl')),/submittedEvidencePreviewHtml/);
assert.match(css,/\.compiled-ep-tile\{[^}]*background:#174d32/);assert.match(css,/\.compiled-ep-actions button\{[^}]*background:#d9efd0[^}]*color:#174d32/);
assert.doesNotMatch(pdf.slice(pdf.indexOf('// Witness testimony:'),pdf.indexOf('// Professional discussion:')),/Photographs|addSubmittedPhotoPages/);
const data='data:audio/webm;base64,AA==',video='data:video/mp4;base64,AA==';
const media=collectPortfolioMedia({walkthrough:[{data:video,type:'video/mp4',code:'S10'}],professionalDiscussion:[{voiceSubmissions:[{data,type:'audio/webm',confirmedCodes:['K22']}]}],practical:[{observerRole:'Assessor',observationRecordings:{LO3:{video:{data:video},audio:{data}}}}]});
assert.deepEqual(media.map(x=>x.reference),['LRV-01','LRA-01'],'legacy observation media is ignored');
assert.deepEqual(['photos','statement','video','audio','document','witness','rpl','glh'].map(nvqEvidenceCodes),['LRP','LRS','LRV','LRA','DOC','WTS','RPL','GLH']);
assert.equal(nvqEvidenceCodes('observation'),'','new observation references cannot be generated');
let records=[{codes:['S10']},{codes:['S10','S11','S10']},{codes:['S10']}];const counts=records=>records.reduce((o,r)=>{for(const c of new Set(r.codes))o[c]=(o[c]||0)+1;return o},{});assert.deepEqual(counts(records),{S10:3,S11:1});
const bytes=new Uint8Array([1,2,3]),u=compileUnitPack({assignmentNumber:1,previewPages:['front','matrix','LRS-01','LRP-01'],entries:[{name:'EP.pdf',data:bytes}]});assert.equal(u.pdfBytes,bytes);assert.deepEqual(compileFullPortfolioFromUnitPacks(['portfolio'],[u]).slice(1),u.previewPages);
const changed=compileUnitPack({assignmentNumber:1,previewPages:['front','matrix','LRS-01 edited','WTS-01'],entries:[{name:'EP.pdf',data:bytes}]});assert.deepEqual(changed.previewPages,['front','matrix','LRS-01 edited','WTS-01']);assert.ok(!changed.previewPages.includes('LRP-01'));
const course={assignments:[{n:1,unit:'U1',title:'Generic',ksbs:[['K1','Knowledge']]}]},matrix=buildKsbMatrixRows(course,course.assignments,[{assignment:1,codes:['K1'],reference:evidenceReference('LRS',1),complete:true}]);assert.equal(matrix[0].count,1);assert.deepEqual(matrix[0].references,['LRS-01']);
const naturalCodes=['K20','S20','B11','K1','S1','B1','K10','S10','B10','K2','S2','B2','K11','S11','K9','S9','B9'];
const naturalCourse={assignments:[{n:1,ksbs:naturalCodes.map(code=>[code,code])}]};assert.deepEqual(buildKsbMatrixRows(naturalCourse,naturalCourse.assignments).map(row=>row.code),['K1','K2','K9','K10','K11','K20','S1','S2','S9','S10','S11','S20','B1','B2','B9','B10','B11']);
const nvqPdf=pdf.slice(pdf.indexOf('async function generateNVQEvidencePackPDF'));
assert.doesNotMatch(nvqPdf,/`AO\$\{|`LS\$\{|`PE\$\{|`VW\$\{|`PD\$\{|`WT\$\{|`SE\$\{/);assert.match(nvqPdf,/Learning Outcome Evidence Matrix/);assert.match(nvqPdf,/Guided Learning Hours/);assert.doesNotMatch(nvqPdf,/K\/S\/B category/);
assert.match(app,/Home/);assert.match(app,/KSB Matrix/);assert.match(app,/Toolkit/);assert.match(app,/COURSE\.nvqUnits\?'GLH':'OTJ'/);assert.match(app,/LO\/AC|Learning Outcome/);
console.log('Evidence taxonomy, WTS ratings/no-photo, LRA terminology, Media audit, EP refresh/parity, KSB/NVQ regressions: PASS');

// V2.83 divider and hierarchical NVQ matrix regressions.
const {compareAssessmentCriterionCodes,assessmentCriteriaForOutcome,buildNvqMatrixGroups,evidencePackTitleModel,estimateNvqMatrixLayout}=require('../pdf-generator.js');
const completedTitle=evidencePackTitleModel({course:{name:'NVQ Diploma'},assignment:{n:2,unit:'234',title:'Masonry cladding'},profile:{fullName:'Alex Learner'},complete:true,completionDate:'10/08/2026'});
assert.deepEqual([completedTitle.code,completedTitle.title,completedTitle.learner,completedTitle.completionDate],['234','Masonry cladding','Alex Learner','10/08/2026']);
const incompleteTitle=evidencePackTitleModel({course:{name:'Standard'},assignment:{n:4,title:'Build safely'},profile:{fullName:'Sam Learner'}});
assert.equal(incompleteTitle.status,'In Progress');assert.equal(incompleteTitle.completionDate,'','incomplete packs never invent completion dates');
const nvqAssignment={n:2,unit:'234',title:'Unit',ksbs:[['LO1','First outcome'],['LO2','Second outcome']],criteria:{LO1:[{code:'1.10',text:'Tenth criterion wording'},{code:'1.1',text:'First criterion wording'},{code:'1.11',text:'Eleventh criterion wording'},{code:'1.9',text:'Ninth criterion wording'},{code:'1.2',text:'Second criterion wording'}],LO2:{'2.2':'Second AC','2.1':'First AC'}}};
assert.deepEqual(['1.1','1.2','1.9','1.10','1.11'].sort(compareAssessmentCriterionCodes),['1.1','1.2','1.9','1.10','1.11']);
const groups=buildNvqMatrixGroups(nvqAssignment,{LO1:[{ref:'WTS-02',type:'WTS'},{ref:'LRP-03',type:'LRP'}],LO2:[{ref:'RPL',type:'RPL'}]},2);
assert.deepEqual(groups[0].criteria.map(x=>x.code),['1.1','1.2','1.9','1.10','1.11']);assert.deepEqual(groups[1].criteria.map(x=>x.code),['2.1','2.2']);
assert.deepEqual(groups[0].criteria[0].references,['WTS-02','LRP-03'],'AC references use only mapped LO evidence');assert.equal(groups[1].criteria[0].references[0],'RPL');assert.equal(groups[1].criteria[0].met,true);
assert.equal(assessmentCriteriaForOutcome(nvqAssignment,'LO1')[0].text,'First criterion wording','complete stored wording remains in the render model');
const longGroups=buildNvqMatrixGroups({ksbs:[['LO1','L'.repeat(600)]],criteria:{LO1:[{code:'1.1',text:'A'.repeat(1600)},{code:'1.2',text:'B'.repeat(1600)}]}},{LO1:[]});const layout=estimateNvqMatrixLayout(longGroups,{lineChars:50,linesPerPage:20});assert.ok(layout.pageCount>=3);assert.equal(layout.blocks.length,2,'long ACs remain present at the data/render layer');
assert.deepEqual(compileFullPortfolioFromUnitPacks(['overall'],[{previewPages:['EP1 divider','EP1 matrix']},{previewPages:['EP2 divider','EP2 matrix']}]),['overall','EP1 divider','EP1 matrix','EP2 divider','EP2 matrix']);
assert.match(app,/class="nvq-lo-group"/);assert.match(app,/ACs met/);assert.match(app,/nvq-lo-expand/);assert.match(css,/\.nvq-lo-group\[open\]/);
assert.match(pdf,/LO → AC → Supporting Evidence/);assert.match(pdf,/✓ Met/);assert.match(pdf,/— Not yet met/);assert.match(pdf,/if\(y\+h>H-112\)start\(true\)/);
assert.match(app,/function assignmentLearningHoursStats/);assert.match(app,/NVQ_ASSESSMENT_CRITERIA/);assert.deepEqual(Object.keys(EVIDENCE_TAXONOMY).filter(code=>code!=='OTJ'),['LRP','LRS','LRV','LRA','DOC','WTS','RPL','GLH']);
console.log('V2.83 divider, portfolio retention, LO/AC grouping, mapping, RPL, wrapping and collapse regressions: PASS');
