'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const app=fs.readFileSync('app.js','utf8');
const pdf=fs.readFileSync('pdf-generator.js','utf8');
const course=fs.readFileSync('course-data.js','utf8');
const assignmentUi=app.slice(app.indexOf('function showVerifiedEvidenceChooser'),app.indexOf('function savedEvidenceTypeLabel'));
for(const term of ['Assessor Observation','Tutor Observation','College Observation','Workplace Observation','data-verified-section="practical"']) assert.doesNotMatch(assignmentUi,new RegExp(term,'i'));
assert.match(assignmentUi,/Employer \/ Witness/);
assert.match(assignmentUi,/data-verified-section="witness"/);
assert.match(assignmentUi,/data-verified-section="rpl"/);
assert.doesNotMatch(course,/"key": "observation"/);
for(const code of ['WOS','WOV','WOA','COS','COV','COA']) assert.equal(pdf.match(new RegExp(`${code}:'`,'g'))?.length||0,0,`${code} absent from generation taxonomy`);
const {EVIDENCE_TAXONOMY,nvqEvidenceCodes,collectPortfolioMedia}=require('../pdf-generator.js');
assert.deepEqual(Object.keys(EVIDENCE_TAXONOMY),['LRP','LRS','LRV','LRA','DOC','WTS','RPL','OTJ','GLH']);
assert.equal(nvqEvidenceCodes('observation'),'');
assert.deepEqual(collectPortfolioMedia({practical:[{observationRecordings:{LO1:{video:{data:'legacy'}}}}]}),[]);
for(const code of ['LRP','LRS','LRV','LRA','DOC','WTS','RPL','OTJ','GLH']) assert.ok(EVIDENCE_TAXONOMY[code]);
assert.match(app,/function renderWitnessPage|function witnessPage/);
assert.match(app,/function renderRplSection/);
assert.match(app,/function nvqLiveCriterionMatrix/);
assert.match(app,/Preview EP/);assert.match(app,/Download EP/);
assert.match(app,/if\(s==='practical'\)\{state\.section=null;state\.view='assignment'/,'legacy route safely redirects');
console.log('Learner-only evidence and legacy observation isolation regressions: PASS');
