const test=require('node:test');
const assert=require('node:assert/strict');

function freshStore(seed={}){const values=new Map(Object.entries(seed));global.localStorage={getItem:k=>values.has(k)?values.get(k):null,setItem:(k,v)=>values.set(k,v)};delete require.cache[require.resolve('../review-transfer.js')];return {api:require('../review-transfer.js'),values}}
const summary=(overrides={})=>({schema:'apprentice-assessor-review',version:2,payloadType:'learner-review-summary',transferId:'tx-1',createdAt:'2026-08-10T10:00:00Z',expiresAt:'2026-08-11T10:00:00Z',learnerLinkId:'link-1',payload:{reviewId:'review-1',reviewDate:'2026-08-10',nextReviewDate:'2026-09-28',overallStatus:'On Track',learnerSummary:'Good progress.',targets:Array.from({length:5},(_,i)=>({targetId:`t${i+1}`,title:`Target ${i+1}`,dueDate:`2026-09-${10+i}`,destination:i?'HOMEWORK':'OTJ',quantity:i?1:6})),...overrides}});

test('V2 snapshot uses exact envelope and reports target outcomes',()=>{const {api}=freshStore();const out=api.makeSnapshot({learner:{linkId:'link-1'},course:{id:'c',title:'Course',type:'KSB'},programme:{startDate:'2026-01-01'},courseProgress:{overall:44,expectedToday:40},learningHours:{type:'OTJ',actual:37},epa:{actualReadiness:31},previousReview:{reviewId:'r0',targets:[{id:'t',status:'completed',completedAt:'2026-08-01',completionEvidence:[{id:'a'}],actualResult:6.5}]}},{createdAt:'2026-08-10T00:00:00Z',expiresAt:'2026-08-11T00:00:00Z'});assert.equal(out.schema,api.SCHEMA);assert.equal(out.version,2);assert.equal(out.payloadType,'progress-snapshot');assert.equal(out.payload.previousReview.targets[0].actualResult,6.5);assert.equal(out.payload.epa.actualReadiness,31)});
test('summary validates, persists additively and survives reload',()=>{const {api}=freshStore();const r=api.importSummary(summary(),{now:Date.parse('2026-08-10T12:00:00Z'),learnerLinkId:'link-1'});assert.equal(r.targets.length,5);assert.ok(r.targets[0].baseline.capturedAt);assert.equal(api.history()[0].reviewId,'review-1');assert.throws(()=>api.importSummary(summary(),{now:Date.parse('2026-08-10T12:00:00Z')}),/already/)});
test('rejects schema, version, type, expiry, learner mismatch and malformed input',()=>{const {api}=freshStore();for(const [field,value] of [['schema','bad'],['version',3],['payloadType','progress-snapshot']])assert.throws(()=>api.importSummary({...summary(),[field]:value},{now:Date.parse('2026-08-10T12:00:00Z')}));assert.throws(()=>api.importSummary({...summary(),expiresAt:'2026-08-09T00:00:00Z'},{now:Date.parse('2026-08-10T12:00:00Z')}),/expired/);assert.throws(()=>api.importSummary(summary(),{now:Date.parse('2026-08-10T12:00:00Z'),learnerLinkId:'other'}),/different learner/);assert.throws(()=>api.importSummary('{'))});
test('countdowns are calculated at render time',()=>{const {api}=freshStore(),d=new Date(2026,7,10,9);assert.equal(api.relativeDate('2026-08-10','target',d),'Due today');assert.equal(api.relativeDate('2026-08-11','target',d),'Tomorrow');assert.equal(api.relativeDate('2026-08-15','target',d),'5 days left');assert.equal(api.relativeDate('2026-08-08','target',d),'2 days overdue');assert.equal(api.relativeDate('2026-08-10','review',d),'Review today')});
test('safe destination routing protects NVQ terminology and no-EPA courses',()=>{const {api}=freshStore();assert.equal(api.routeFor('OTJ',false),'otjmate');assert.equal(api.routeFor('GLH',true),'otjmate');assert.equal(api.routeFor('GLH',false),null);assert.equal(api.routeFor('LO_AC',true),'epa');assert.equal(api.routeFor('EPA_MCQ',true),null);assert.equal(api.routeFor('UNKNOWN'),null)});
test('baseline blocks old activity and OTJ, GLH, EPA, KSB and activity rules complete on new work',()=>{const {api}=freshStore(),base={capturedAt:'2026-08-10T00:00:00Z',completedIds:['K1']};for(const kind of ['OTJ','GLH']){const t={id:kind,destination:kind,quantity:6,baseline:base,status:'in-progress'};assert.equal(api.evaluateTarget(t,{[kind]:[{id:'old',createdAt:'2026-08-09',hours:9}]}).status,'in-progress');assert.equal(api.evaluateTarget(t,{[kind]:[{id:'new',createdAt:'2026-08-11',hours:6.5}]}).status,'completed')};for(const kind of ['EPA_MCQ','EPA_PRACTICE','KNOWLEDGE_SLIDES','HOMEWORK','CERTIFICATE','LRP','LRS','LRV','LRA'])assert.equal(api.evaluateTarget({destination:kind,quantity:1,baseline:base,status:'in-progress'},{[kind]:[{id:'new',createdAt:'2026-08-11',score:84}]}).status,'completed');assert.equal(api.evaluateTarget({destination:'KSB_COUNT',quantity:2,baseline:base,status:'in-progress'},{completedCriteria:[{id:'K1'},{id:'S2'},{id:'B3'}]}).status,'completed')});
test('next-review marker calculation is timeline-based and clamps',()=>{const {api}=freshStore();assert.equal(api.expectedAtReview('2026-01-01','2026-11-01','2026-06-01'),50);assert.equal(api.expectedAtReview('2026-01-01','2026-11-01','2027-01-01'),100);assert.equal(api.expectedAtReview('','',''),null)});
test('legacy ReviewMate outcome data is preserved and exposed under Reviews',()=>{const legacy=JSON.stringify([{reviewId:'old',reviewDate:'2025-01-01',tutorSummary:'Legacy',targets:[{text:'Old target'}]}]);const {api}=freshStore({'apprenticePlus:receivedReviewOutcomes:v1':legacy});assert.equal(api.history()[0].legacy,true);assert.equal(api.history()[0].learnerSummary,'Legacy')});

test('only latest authoritative V2 review drives Home targets while history stays additive',()=>{
 const {api,values}=freshStore({'apprenticePlus:receivedReviewOutcomes:v1':JSON.stringify([{reviewId:'legacy',reviewDate:'2026-01-01',targets:Array.from({length:5},(_,i)=>({text:`Old ${i}`}))}])});
 assert.equal(api.latest(),null);
 api.importSummary(summary(),{learnerLinkId:'link-1'});
 const newer=summary({reviewId:'review-2',reviewDate:'2026-08-20',targets:Array.from({length:5},(_,i)=>({targetId:`new${i}`,title:`New ${i+1}`,destination:'HOMEWORK'}))});newer.transferId='tx-2';api.importSummary(newer,{learnerLinkId:'link-1'});
 assert.equal(api.history().length,3);
 assert.equal(api.latest().reviewId,'review-2');
 assert.deepEqual(api.latest().targets.map(x=>x.title),['New 1','New 2','New 3','New 4','New 5']);
 assert.ok(values.get(api.HISTORY_KEY));
});

test('learner-facing errors remain enforceable for duplicate, learner and expiry rules',()=>{
 const {api}=freshStore();api.importSummary(summary(),{learnerLinkId:'link-1'});
 assert.throws(()=>api.importSummary(summary(),{learnerLinkId:'link-1'}),/already/i);
 assert.throws(()=>api.importSummary(summary({reviewId:'other'}),{learnerLinkId:'link-2'}),/different learner/i);
 assert.throws(()=>api.importSummary(summary({reviewId:'expired'}),{learnerLinkId:'link-1',now:Date.parse('2026-08-12')}),/expired/i);
});
